// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SubscribePricesRequest {
    #[prost(string, repeated, tag = "1")]
    pub symbols: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UnsubscribePricesRequest {
    #[prost(string, repeated, tag = "1")]
    pub symbols: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ClearSubscriptionRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Empty {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetAlertRequest {
    /// optional: if empty server generates
    #[prost(string, tag = "1")]
    pub alert_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub symbol: ::prost::alloc::string::String,
    /// threshold
    #[prost(double, tag = "3")]
    pub price: f64,
    /// ABOVE / BELOW
    #[prost(string, tag = "4")]
    pub kind: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RemoveAlertRequest {
    #[prost(string, tag = "1")]
    pub alert_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AlertResult {
    #[prost(string, tag = "1")]
    pub alert_id: ::prost::alloc::string::String,
    /// UPDATED / TRIGGERED / REMOVED
    #[prost(string, tag = "2")]
    pub status: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub symbol: ::prost::alloc::string::String,
    /// price related to alert state
    #[prost(double, tag = "4")]
    pub ref_price: f64,
    #[prost(int64, tag = "5")]
    pub ts_ms: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PriceTick {
    #[prost(string, tag = "1")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(double, tag = "2")]
    pub bid: f64,
    #[prost(double, tag = "3")]
    pub ask: f64,
    #[prost(int64, tag = "4")]
    pub ts_ms: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CommandAck {
    /// ALERT_SET / ALERT_REMOVED / SUBSCRIBED / PONG / ERROR
    #[prost(string, tag = "1")]
    pub kind: ::prost::alloc::string::String,
    /// alert_id or detail
    #[prost(string, tag = "2")]
    pub reference: ::prost::alloc::string::String,
}
/// Query current latest bid/ask for a symbol.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetPriceRequest {
    #[prost(string, tag = "1")]
    pub symbol: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPriceResponse {
    #[prost(string, tag = "1")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(double, tag = "2")]
    pub bid: f64,
    #[prost(double, tag = "3")]
    pub ask: f64,
    /// timestamp of snapshot (server current time)
    #[prost(int64, tag = "4")]
    pub ts_ms: i64,
    /// false if symbol unknown or no price yet
    #[prost(bool, tag = "5")]
    pub found: bool,
}
/// Batch price query
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetPricesRequest {
    #[prost(string, repeated, tag = "1")]
    pub symbols: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PriceSnapshot {
    #[prost(string, tag = "1")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(double, tag = "2")]
    pub bid: f64,
    #[prost(double, tag = "3")]
    pub ask: f64,
    #[prost(int64, tag = "4")]
    pub ts_ms: i64,
    #[prost(bool, tag = "5")]
    pub found: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPricesResponse {
    #[prost(message, repeated, tag = "1")]
    pub prices: ::prost::alloc::vec::Vec<PriceSnapshot>,
}
/// Get list of available symbols
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetSymbolListRequest {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetSymbolListResponse {
    #[prost(string, repeated, tag = "1")]
    pub symbols: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// Get market connection state
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetStateRequest {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetStateResponse {
    /// CONNECTED / DISCONNECTED / CONNECTING / LOGON
    #[prost(string, tag = "1")]
    pub state: ::prost::alloc::string::String,
    /// timestamp of state
    #[prost(int64, tag = "2")]
    pub ts_ms: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StreamCommand {
    #[prost(oneof = "stream_command::Cmd", tags = "1, 2, 3, 4, 5, 6")]
    pub cmd: ::core::option::Option<stream_command::Cmd>,
}
/// Nested message and enum types in `StreamCommand`.
pub mod stream_command {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Cmd {
        #[prost(message, tag = "1")]
        SubscribePrices(super::SubscribePricesRequest),
        #[prost(message, tag = "2")]
        SetAlert(super::SetAlertRequest),
        #[prost(message, tag = "3")]
        RemoveAlert(super::RemoveAlertRequest),
        #[prost(message, tag = "4")]
        Ping(super::Empty),
        #[prost(message, tag = "5")]
        UnsubscribePrices(super::UnsubscribePricesRequest),
        #[prost(message, tag = "6")]
        ClearSubscription(super::ClearSubscriptionRequest),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StreamEvent {
    #[prost(oneof = "stream_event::Evt", tags = "1, 2, 3")]
    pub evt: ::core::option::Option<stream_event::Evt>,
}
/// Nested message and enum types in `StreamEvent`.
pub mod stream_event {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Evt {
        #[prost(message, tag = "1")]
        PriceTick(super::PriceTick),
        #[prost(message, tag = "2")]
        Alert(super::AlertResult),
        #[prost(message, tag = "3")]
        Ack(super::CommandAck),
    }
}
/// Generated client implementations.
pub mod market_stream_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct MarketStreamClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl MarketStreamClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> MarketStreamClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> MarketStreamClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            MarketStreamClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Bidirectional stream: client sends commands, server sends events.
        pub async fn stream(
            &mut self,
            request: impl tonic::IntoStreamingRequest<Message = super::StreamCommand>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::StreamEvent>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/quant.MarketStream/Stream",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut().insert(GrpcMethod::new("quant.MarketStream", "Stream"));
            self.inner.streaming(req, path, codec).await
        }
        /// Unary price snapshot
        pub async fn get_price(
            &mut self,
            request: impl tonic::IntoRequest<super::GetPriceRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetPriceResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/quant.MarketStream/GetPrice",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("quant.MarketStream", "GetPrice"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_prices(
            &mut self,
            request: impl tonic::IntoRequest<super::GetPricesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetPricesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/quant.MarketStream/GetPrices",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("quant.MarketStream", "GetPrices"));
            self.inner.unary(req, path, codec).await
        }
        /// Get available symbol list
        pub async fn get_symbol_list(
            &mut self,
            request: impl tonic::IntoRequest<super::GetSymbolListRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetSymbolListResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/quant.MarketStream/GetSymbolList",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("quant.MarketStream", "GetSymbolList"));
            self.inner.unary(req, path, codec).await
        }
        /// Get market connection state
        pub async fn get_state(
            &mut self,
            request: impl tonic::IntoRequest<super::GetStateRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetStateResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/quant.MarketStream/GetState",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("quant.MarketStream", "GetState"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod market_stream_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with MarketStreamServer.
    #[async_trait]
    pub trait MarketStream: std::marker::Send + std::marker::Sync + 'static {
        /// Server streaming response type for the Stream method.
        type StreamStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::StreamEvent, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// Bidirectional stream: client sends commands, server sends events.
        async fn stream(
            &self,
            request: tonic::Request<tonic::Streaming<super::StreamCommand>>,
        ) -> std::result::Result<tonic::Response<Self::StreamStream>, tonic::Status>;
        /// Unary price snapshot
        async fn get_price(
            &self,
            request: tonic::Request<super::GetPriceRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetPriceResponse>,
            tonic::Status,
        >;
        async fn get_prices(
            &self,
            request: tonic::Request<super::GetPricesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetPricesResponse>,
            tonic::Status,
        >;
        /// Get available symbol list
        async fn get_symbol_list(
            &self,
            request: tonic::Request<super::GetSymbolListRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetSymbolListResponse>,
            tonic::Status,
        >;
        /// Get market connection state
        async fn get_state(
            &self,
            request: tonic::Request<super::GetStateRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetStateResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct MarketStreamServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> MarketStreamServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for MarketStreamServer<T>
    where
        T: MarketStream,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/quant.MarketStream/Stream" => {
                    #[allow(non_camel_case_types)]
                    struct StreamSvc<T: MarketStream>(pub Arc<T>);
                    impl<
                        T: MarketStream,
                    > tonic::server::StreamingService<super::StreamCommand>
                    for StreamSvc<T> {
                        type Response = super::StreamEvent;
                        type ResponseStream = T::StreamStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                tonic::Streaming<super::StreamCommand>,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MarketStream>::stream(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = StreamSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/quant.MarketStream/GetPrice" => {
                    #[allow(non_camel_case_types)]
                    struct GetPriceSvc<T: MarketStream>(pub Arc<T>);
                    impl<
                        T: MarketStream,
                    > tonic::server::UnaryService<super::GetPriceRequest>
                    for GetPriceSvc<T> {
                        type Response = super::GetPriceResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetPriceRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MarketStream>::get_price(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetPriceSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/quant.MarketStream/GetPrices" => {
                    #[allow(non_camel_case_types)]
                    struct GetPricesSvc<T: MarketStream>(pub Arc<T>);
                    impl<
                        T: MarketStream,
                    > tonic::server::UnaryService<super::GetPricesRequest>
                    for GetPricesSvc<T> {
                        type Response = super::GetPricesResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetPricesRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MarketStream>::get_prices(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetPricesSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/quant.MarketStream/GetSymbolList" => {
                    #[allow(non_camel_case_types)]
                    struct GetSymbolListSvc<T: MarketStream>(pub Arc<T>);
                    impl<
                        T: MarketStream,
                    > tonic::server::UnaryService<super::GetSymbolListRequest>
                    for GetSymbolListSvc<T> {
                        type Response = super::GetSymbolListResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetSymbolListRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MarketStream>::get_symbol_list(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetSymbolListSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/quant.MarketStream/GetState" => {
                    #[allow(non_camel_case_types)]
                    struct GetStateSvc<T: MarketStream>(pub Arc<T>);
                    impl<
                        T: MarketStream,
                    > tonic::server::UnaryService<super::GetStateRequest>
                    for GetStateSvc<T> {
                        type Response = super::GetStateResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetStateRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MarketStream>::get_state(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetStateSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for MarketStreamServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "quant.MarketStream";
    impl<T> tonic::server::NamedService for MarketStreamServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
